### Kansas City, St. Louis, and Springfield

In [1]:
import pandas as pd
import numpy as np
import re
from difflib import get_close_matches

In [2]:
kc = pd.read_csv(
    'auction_data/kcmo.csv',
    dtype={"Zip":"string"})
stl = pd.read_csv('auction_data/stl.csv')
spfd = pd.read_csv('auction_data/springfield.csv')

#### Add unique ID's & Market info to each county csv

In [3]:
#KC

# Create APN column
kc["APN"] = (
    "KCMO."
    + kc["Address"]
        .fillna("")
        .str.replace(" ", "_",regex = False)
        .str.upper()
    +"_"
    + kc["Zip"].astype(str).str.replace(r"\.0$", "", regex=True)
)

#Create Market column
kc["Market"] = "Kansas City"

In [4]:
kc.head()

,County,Date,Time,Address,City,Zip,Owner Name,Mailing Address,Bedrooms,Bathrooms,...,Opening Bid,Assessed Value,Proj. Opening Bid,Original Loan Amount,APN Number,Status,Action,Comments,APN,Market
0,Jackson County,10-05-2026,10:00,8605 E 81st Ter,Raytown,64138,Raymond P Hatfield and Peggy M Hatfield,"8605 E 81st Ter, Raytown, MO 64138",3.0,1.0,...,NaN,226300.0,NaN,NaN,45-940-05-10-00-0-00-000,Active,NaN,NaN,KCMO.8605_E_81ST_TER_64138,Kansas City
1,Jackson County,10-05-2026,14:00,5635 E 27th St,Kansas City,64127,Benjamin Castaneda aka Benjamin Castaneda Ariendo,"5635 E 27th St, Kansas City, MO 64127",2.0,1.0,...,NaN,105200.0,45357.0,53531.0,28-810-01-26-00-0-00-000,Active,NaN,NaN,KCMO.5635_E_27TH_ST_64127,Kansas City
2,Jackson County,10-05-2026,15:00,11610 Blue Ridge Blvd,Kansas City,64134,Mabel Molina,"11610 Blue Ridge Blvd, Kansas City, MO 64134",2.0,1.0,...,79410.73,196600.0,39098.0,68880.0,64-620-04-14-00-0-00-000,Active,NaN,NaN,KCMO.11610_BLUE_RIDGE_BLVD_64134,Kansas City
3,Clinton County,10-06-2026,11:00,6741 SE Horseshoe Dr,Holts Summit,64048,Everett William Downs,"6741 SE Horseshoe Dr, Holt, MO 64048",NaN,3.0,...,NaN,335800.0,67385.0,70000.0,15-06.1-24-003-002-036.000,Canceled,NaN,NaN,KCMO.6741_SE_HORSESHOE_DR_64048,Kansas City
4,Clinton County,10-06-2026,11:00,615 W Maple St,Plattsburg,64477,Katharine L Sammons,"615 W Maple St, Plattsburg, MO 64477",NaN,1.0,...,NaN,120800.0,NaN,NaN,11-06.0-23-001-040-007.000,Active,NaN,NaN,KCMO.615_W_MAPLE_ST_64477,Kansas City

In [5]:
#STL

# Create APN column
stl["APN"] = (
    "STL_MO."
    + stl["Address"]
        .fillna("")
        .str.replace(" ", "_",regex = False)
        .str.upper()
    +"_"
    + stl["Zip"].astype(str)
)

#Create Market column
stl["Market"] = "St. Louis"

In [6]:
stl.head()

,County,Date,Time,Address,City,Zip,Owner Name,Mailing Address,Bedrooms,Bathrooms,...,Opening Bid,Assessed Value,Proj. Opening Bid,Original Loan Amount,APN Number,Status,Action,Comments,APN,Market
0,St. Louis City,10-05-2026,09:00,3911 Eiler St,St. Louis,63116,James D Sallis,"3911 Eiler St, Saint Louis, MO 63116",2.0,1.0,...,109265.00,153000,113040.0,127000.0,5792-00-0230-0,Active,NaN,NaN,STL_MO.3911_EILER_ST_63116,St. Louis
1,St. Louis City,10-05-2026,09:00,5087 Cates Ave,St. Louis,63108,Travis Watson,"5087 Cates Ave, Saint Louis, MO 63108",3.0,2.0,...,NaN,173300,180789.0,184500.0,4840-00-0535-0,Canceled,NaN,NaN,STL_MO.5087_CATES_AVE_63108,St. Louis
2,St. Louis City,10-05-2026,09:00,1235 Clara Ave,St. Louis,63112,Shawn Harrell and Denecia Ann Billups,"1235 Clara Ave, Saint Louis, MO 63112",5.0,1.0,...,104262.28,203500,93416.0,110000.0,3815-08-0210-0,Canceled,NaN,NaN,STL_MO.1235_CLARA_AVE_63112,St. Louis
3,Jefferson County,10-05-2026,09:00,10573 Turnberry Ct,Festus,63028,Jeannie Baumgartner-Theiling,"9619 E Vista Dr Hillsboro, MO 63050",4.0,5.0,...,NaN,688500,316105.0,333000.0,18-2.0-03.0-0-000-008.25,Active,NaN,NaN,STL_MO.10573_TURNBERRY_CT_63028,St. Louis
4,St. Louis County,10-05-2026,10:00,603 Butler Dr,Eureka,63025,Bryan L Jeffryes and Elizabeth A Jeffryes,"603 Butler Dr, Eureka, MO 63025",3.0,1.0,...,NaN,226600,NaN,NaN,29V-21-0355,Canceled,NaN,NaN,STL_MO.603_BUTLER_DR_63025,St. Louis

In [7]:
#Springfield

# Create APN column
spfd["APN"] = (
    "SPRINGFIELD_MO."
    + spfd["Address"]
        .fillna("")
        .str.replace(" ", "_",regex = False)
        .str.upper()
    +"_"
    + spfd["Zip"].astype(str)
)

#Create Market column
spfd["Market"] = "Springfield"

In [8]:
spfd.head()

Empty DataFrame
Columns: [County, Date, Time, Address, City, Zip, Owner Name, Mailing Address, Bedrooms, Bathrooms, Square Feet, Taxes, Title Comments, Occupancy Status, Trustee, File #, Opening Bid, Assessed Value, Proj. Opening Bid, Original Loan Amount, APN Number, Status, Action, Comments, APN, Market]
Index: []

[0 rows x 26 columns]

#### Combine all data to one csv

In [9]:
davidimport = pd.concat([kc, stl, spfd], ignore_index=True)

davidimport.to_csv("export_data/davidimport.csv", index=False)

/var/folders/0v/2p48l9mx23dc0422gf24z_qr0000gn/T/ipykernel_94177/3750653891.py:1: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  davidimport = pd.concat([kc, stl, spfd], ignore_index=True)

In [10]:
#Find duplicate APNs

duplicate_apns = davidimport[
    davidimport.duplicated(subset="APN", keep=False)
]

# View them
duplicate_apns.sort_values("APN")

Empty DataFrame
Columns: [County, Date, Time, Address, City, Zip, Owner Name, Mailing Address, Bedrooms, Bathrooms, Square Feet, Taxes, Title Comments, Occupancy Status, Trustee, File #, Opening Bid, Assessed Value, Proj. Opening Bid, Original Loan Amount, APN Number, Status, Action, Comments, APN, Market]
Index: []

[0 rows x 26 columns]

In [11]:
#Remove duplicate apns

davidimport.drop_duplicates(['APN'], keep = 'first', inplace=True)

#### Add Columns
County, Last Name

In [12]:
#Full address
#Labeled as 'Last Name' for Salesforce Lead object purposes

davidimport["Last Name"] = (
    davidimport["Address"].fillna("").astype(str)
    + ", "
    + davidimport["City"].fillna("").astype(str)
    + ", MO "
    + davidimport["Zip"].fillna("").astype(str)
)

davidimport["Last Name"] = davidimport["Last Name"]

In [13]:
davidimport.head()

,County,Date,Time,Address,City,Zip,Owner Name,Mailing Address,Bedrooms,Bathrooms,...,Assessed Value,Proj. Opening Bid,Original Loan Amount,APN Number,Status,Action,Comments,APN,Market,Last Name
0,Jackson County,10-05-2026,10:00,8605 E 81st Ter,Raytown,64138,Raymond P Hatfield and Peggy M Hatfield,"8605 E 81st Ter, Raytown, MO 64138",3.0,1.0,...,226300.0,NaN,NaN,45-940-05-10-00-0-00-000,Active,NaN,NaN,KCMO.8605_E_81ST_TER_64138,Kansas City,"8605 E 81st Ter, Raytown, MO 64138"
1,Jackson County,10-05-2026,14:00,5635 E 27th St,Kansas City,64127,Benjamin Castaneda aka Benjamin Castaneda Ariendo,"5635 E 27th St, Kansas City, MO 64127",2.0,1.0,...,105200.0,45357.0,53531.0,28-810-01-26-00-0-00-000,Active,NaN,NaN,KCMO.5635_E_27TH_ST_64127,Kansas City,"5635 E 27th St, Kansas City, MO 64127"
2,Jackson County,10-05-2026,15:00,11610 Blue Ridge Blvd,Kansas City,64134,Mabel Molina,"11610 Blue Ridge Blvd, Kansas City, MO 64134",2.0,1.0,...,196600.0,39098.0,68880.0,64-620-04-14-00-0-00-000,Active,NaN,NaN,KCMO.11610_BLUE_RIDGE_BLVD_64134,Kansas City,"11610 Blue Ridge Blvd, Kansas City, MO 64134"
3,Clinton County,10-06-2026,11:00,6741 SE Horseshoe Dr,Holts Summit,64048,Everett William Downs,"6741 SE Horseshoe Dr, Holt, MO 64048",NaN,3.0,...,335800.0,67385.0,70000.0,15-06.1-24-003-002-036.000,Canceled,NaN,NaN,KCMO.6741_SE_HORSESHOE_DR_64048,Kansas City,"6741 SE Horseshoe Dr, Holts Summit, MO 64048"
4,Clinton County,10-06-2026,11:00,615 W Maple St,Plattsburg,64477,Katharine L Sammons,"615 W Maple St, Plattsburg, MO 64477",NaN,1.0,...,120800.0,NaN,NaN,11-06.0-23-001-040-007.000,Active,NaN,NaN,KCMO.615_W_MAPLE_ST_64477,Kansas City,"615 W Maple St, Plattsburg, MO 64477"

In [14]:
#County
#All of the values contain county at the end, so I want to remove that

davidimport["County"] = davidimport["County"].str.replace(" County", "", regex=False)

In [15]:
#Change currency columns to numbers

for col in ["Opening Bid"]:
    davidimport.loc[:, col] = (
        davidimport[col]
        .astype(str)
        .str.replace(r"[\$,]", "", regex=True)
        .astype(float)
    )

In [16]:
davidimport.loc[
    davidimport["Status"] == "Canceled",
    ["Status", "Opening Bid"]
].head(20)

       Status  Opening Bid
3    Canceled          NaN
14   Canceled     40612.16
15   Canceled          NaN
20   Canceled          NaN
45   Canceled          NaN
90   Canceled          NaN
103  Canceled          NaN
106  Canceled          NaN
111  Canceled          NaN
112  Canceled    104262.28
114  Canceled          NaN
115  Canceled          NaN
120  Canceled    129639.73
121  Canceled          NaN
122  Canceled          NaN
123  Canceled          NaN
124  Canceled          NaN
126  Canceled     89500.00
127  Canceled    781665.00
128  Canceled          NaN

In [17]:
#Update Auction Status 

davidimport["Status"] = np.where(
    davidimport["Status"] == "Canceled",
    "Cancelled",
    ""
)

In [18]:
#Update Opening Bid

davidimport["Opening Bid"] = davidimport["Opening Bid"].astype("string")

davidimport.loc[
    davidimport["Status"].str.strip().str.upper() == "CANCELLED",
    "Opening Bid"
] = ""

In [19]:
davidimport.loc[
    davidimport["Status"] == "Cancelled",
    ["Status", "Opening Bid"]
].head(20)

        Status Opening Bid
3    Cancelled
14   Cancelled
15   Cancelled
20   Cancelled
45   Cancelled
90   Cancelled
103  Cancelled
106  Cancelled
111  Cancelled
112  Cancelled
114  Cancelled
115  Cancelled
120  Cancelled
121  Cancelled
122  Cancelled
123  Cancelled
124  Cancelled
126  Cancelled
127  Cancelled
128  Cancelled

In [20]:
#Change column names
davidimport = davidimport.rename(columns={
    "Date": "Auction Date Updated",
    "Time": "Auction Sale Time",
    "Owner Name": "Property Owner Name",
    "Square Feet": "Bldg Sq Ft",
    "Trustee": "Auction Trustee",
    "File #": "NS Trustee Sale Number",
    "Opening Bid": "Auction Opening Bid",
    "Status": "Auction Status",
    "Bedrooms": "Beds",
    "Bathrooms": "Baths",
    "APN Number": "Tax ID",
    "Assessed Value": "Estimated Value",
    "Original Loan Amount": "Mortgage $"
})

In [21]:
davidimport.head()

,County,Auction Date Updated,Auction Sale Time,Address,City,Zip,Property Owner Name,Mailing Address,Beds,Baths,...,Estimated Value,Proj. Opening Bid,Mortgage $,Tax ID,Auction Status,Action,Comments,APN,Market,Last Name
0,Jackson,10-05-2026,10:00,8605 E 81st Ter,Raytown,64138,Raymond P Hatfield and Peggy M Hatfield,"8605 E 81st Ter, Raytown, MO 64138",3.0,1.0,...,226300.0,NaN,NaN,45-940-05-10-00-0-00-000,,NaN,NaN,KCMO.8605_E_81ST_TER_64138,Kansas City,"8605 E 81st Ter, Raytown, MO 64138"
1,Jackson,10-05-2026,14:00,5635 E 27th St,Kansas City,64127,Benjamin Castaneda aka Benjamin Castaneda Ariendo,"5635 E 27th St, Kansas City, MO 64127",2.0,1.0,...,105200.0,45357.0,53531.0,28-810-01-26-00-0-00-000,,NaN,NaN,KCMO.5635_E_27TH_ST_64127,Kansas City,"5635 E 27th St, Kansas City, MO 64127"
2,Jackson,10-05-2026,15:00,11610 Blue Ridge Blvd,Kansas City,64134,Mabel Molina,"11610 Blue Ridge Blvd, Kansas City, MO 64134",2.0,1.0,...,196600.0,39098.0,68880.0,64-620-04-14-00-0-00-000,,NaN,NaN,KCMO.11610_BLUE_RIDGE_BLVD_64134,Kansas City,"11610 Blue Ridge Blvd, Kansas City, MO 64134"
3,Clinton,10-06-2026,11:00,6741 SE Horseshoe Dr,Holts Summit,64048,Everett William Downs,"6741 SE Horseshoe Dr, Holt, MO 64048",NaN,3.0,...,335800.0,67385.0,70000.0,15-06.1-24-003-002-036.000,Cancelled,NaN,NaN,KCMO.6741_SE_HORSESHOE_DR_64048,Kansas City,"6741 SE Horseshoe Dr, Holts Summit, MO 64048"
4,Clinton,10-06-2026,11:00,615 W Maple St,Plattsburg,64477,Katharine L Sammons,"615 W Maple St, Plattsburg, MO 64477",NaN,1.0,...,120800.0,NaN,NaN,11-06.0-23-001-040-007.000,,NaN,NaN,KCMO.615_W_MAPLE_ST_64477,Kansas City,"615 W Maple St, Plattsburg, MO 64477"

#### Auction Trustee Lookups

In [22]:
contacts = pd.read_csv('sf_data/trusteecontacts.csv')

In [23]:
# Clean up column names if there are leading/trailing spaces
#contacts.columns = contacts.columns.str.strip()

In [24]:
#Normalize text for Contact Name and Associated Names

def norm(s):
    if pd.isna(s):
        return ""
    s = str(s).upper()
    s = s.replace("\u00A0", " ")              # non-breaking spaces
    s = re.sub(r"[^\w\s]", " ", s)            # remove punctuation
    s = re.sub(r"\s+", " ", s).strip()        # collapse spaces
    return s

contacts["contact_name_norm"] = contacts["Contact: Contact Name"].map(norm)
contacts["assoc_norm"] = contacts["Associated Names"].map(norm)  # can be blank

In [25]:
#contacts["contact_name_norm"] = contacts["Contact: Contact Name"]
#contacts["assoc_norm"] = contacts["Associated Names"]
#davidimport["trustee_norm"] = davidimport["Auction Trustee"]

In [26]:
#Normalize trustee names in the auction data

davidimport["trustee_norm"] = davidimport["Auction Trustee"].map(norm)

In [27]:
#Find exact matches

exact_map = dict(zip(contacts["contact_name_norm"], contacts["Contact: Contact Name"]))
davidimport["Auction Trustee (Lookup)"] = davidimport["trustee_norm"].map(exact_map)

In [28]:
#Find contains matches

def contains_in_contact_name(trustee_norm_value: str):
    if not trustee_norm_value:
        return None

    # find first contact where contact name contains trustee value
    hits = contacts.loc[
        contacts["contact_name_norm"].str.contains(re.escape(trustee_norm_value), na=False),
        "Contact: Contact Name"
    ]
    return hits.iloc[0] if len(hits) else None

mask = davidimport["Auction Trustee (Lookup)"].isna() & (davidimport["trustee_norm"] != "")
davidimport.loc[mask, "Auction Trustee (Lookup)"] = davidimport.loc[mask, "trustee_norm"].map(contains_in_contact_name)

In [29]:
#Find contains matches in associated names

def contains_in_associated(trustee_norm_value: str):
    if not trustee_norm_value:
        return None

    hits = contacts.loc[
        contacts["assoc_norm"].str.contains(re.escape(trustee_norm_value), na=False),
        "Contact: Contact Name"
    ]
    return hits.iloc[0] if len(hits) else None

mask = davidimport["Auction Trustee (Lookup)"].isna() & (davidimport["trustee_norm"] != "")
davidimport.loc[mask, "Auction Trustee (Lookup)"] = davidimport.loc[mask, "trustee_norm"].map(contains_in_associated)

In [30]:
#Collect and show unmatched rows

unmatched = (
    davidimport.loc[davidimport["Auction Trustee (Lookup)"].isna(),["Last Name", "Auction Trustee", "trustee_norm"]])

unmatched

,Last Name,Auction Trustee,trustee_norm
1,"5635 E 27th St, Kansas City, MO 64127","John R. Campbell, Jr",JOHN R CAMPBELL JR
30,"1311 E 24th St, Kansas City, MO 64108","singers corp, By: /s/ Michael P. Gaughan",SINGERS CORP BY S MICHAEL P GAUGHAN
58,"11713 Easley Dr, Lees Summit, MO 64086",JOHN H. EDMISTON,JOHN H EDMISTON
84,"925 Grand Blvd, Kansas City, MO 64106",CENTRE TRUSTEE CORP. By: Michele M. OMalley,CENTRE TRUSTEE CORP BY MICHELE M OMALLEY
116,"829 W Main St, Festus, MO 63028","singers corp By, Michael P. Gaughan",SINGERS CORP BY MICHAEL P GAUGHAN
148,"421 Bluff Meadow Dr, Ellisville, MO 63021","The Schnaare Law Firm, P.C",THE SCHNAARE LAW FIRM P C
153,"414 Watson Rd, Sullivan, MO 63080",John B Loveless,JOHN B LOVELESS
179,"612 N 5th St, Elsberry, MO 63343","LCB, LLC",LCB LLC
196,"825 Hornsby Ave, St. Louis, MO 63147","St. Louis Investment Properties, Inc",ST LOUIS INVESTMENT PROPERTIES INC
208,"150 Shepley Dr, St. Louis, MO 63137","St. Louis Investment Properties, Inc",ST LOUIS INVESTMENT PROPERTIES INC
251,"5340 Delmar Blvd, St. Louis, MO 63112",William J. Easley BC,WILLIAM J EASLEY BC
254,"132 Coil Rd, Fenton, MO 63026",Scott M. McKinnis,SCOTT M MCKINNIS
261,"5328 Delmar Blvd, St. Louis, MO 63112","William J. Easley BC TRUSTEE SERVICES, INC",WILLIAM J EASLEY BC TRUSTEE SERVICES INC
317,"2527 Golden Gate Dr, Imperial, MO 63052","Dayid L Marshak, Sheriff",DAYID L MARSHAK SHERIFF

In [31]:
#Confirm what should match but didnt

missing = (
    davidimport.loc[davidimport["Auction Trustee (Lookup)"].isna(), "trustee_norm"]
    .dropna().drop_duplicates()
)

# which of these are present as a normalized contact name?
present_mask = missing.isin(contacts["contact_name_norm"])
missing_not_in_contacts = missing[~present_mask]

missing_not_in_contacts.head(50)

1                            JOHN R CAMPBELL JR
30          SINGERS CORP BY S MICHAEL P GAUGHAN
58                              JOHN H EDMISTON
84     CENTRE TRUSTEE CORP BY MICHELE M OMALLEY
116           SINGERS CORP BY MICHAEL P GAUGHAN
148                   THE SCHNAARE LAW FIRM P C
153                             JOHN B LOVELESS
179                                     LCB LLC
196          ST LOUIS INVESTMENT PROPERTIES INC
251                         WILLIAM J EASLEY BC
254                            SCOTT M MCKINNIS
261    WILLIAM J EASLEY BC TRUSTEE SERVICES INC
317                     DAYID L MARSHAK SHERIFF
Name: trustee_norm, dtype: object

In [32]:
davidimport.to_csv("export_data/davidimport.csv", index=False)